# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cfar_processing": "01_radardsp.ipynb"}

modules = ["radardsp.py",
           "h5dataset.py",
           "geometry.py"]

doc_url = "https://moodoki.github.io/radicalsdk/"

git_url = "https://github.com/moodoki/radicalsdk/tree/master/"

def custom_doc_links(name): return None
