# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cfar_processing": "radardsp.ipynb"}

modules = ["h5dataset.py",
           "radardsp.py"]

doc_url = "https://moodoki.github.io/radicalsdk/"

git_url = "https://github.com/moodoki/radicalsdk/tree/master/"

def custom_doc_links(name): return None
