# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"cfar_nms": "01_radardsp.ipynb",
         "range_azimuth_ca_cfar": "01_radardsp.ipynb",
         "range_azimuth_os_cfar": "01_radardsp.ipynb",
         "logger": "04_radarcfg_v1.ipynb",
         "H5DatasetIterator": "02_h5dataset.ipynb",
         "H5DatasetLoader": "02_h5dataset.ipynb",
         "PolarToCartesianWarp": "03_geometry.ipynb",
         "CameraRadarCoordinateTransform": "03_geometry.ipynb",
         "compute_radar_intrinsic_matrix": "03_geometry.ipynb",
         "read_radar_params": "04_radarcfg_v1.ipynb",
         "parse_commands": "04_radarcfg_v1.ipynb",
         "dict_to_list": "04_radarcfg_v1.ipynb",
         "channelStr_to_dict": "04_radarcfg_v1.ipynb",
         "profileStr_to_dict": "04_radarcfg_v1.ipynb",
         "chirp_to_dict": "04_radarcfg_v1.ipynb",
         "power_to_dict": "04_radarcfg_v1.ipynb",
         "frameStr_to_dict": "04_radarcfg_v1.ipynb",
         "adcStr_to_dict": "04_radarcfg_v1.ipynb",
         "command_handlers": "04_radarcfg_v1.ipynb",
         "RadarFrame": "05_radarv1.ipynb",
         "cov_matrix": "06_beamformers.ipynb",
         "forward_backward_avg": "06_beamformers.ipynb",
         "aoa_capon": "06_beamformers.ipynb"}

modules = ["radardsp.py",
           "h5dataset.py",
           "geometry.py",
           "radar/config_v1.py",
           "radar/v1.py",
           "beamformers.py"]

doc_url = "https://moodoki.github.io/radical_sdk/"

git_url = "https://github.com/moodoki/radical_sdk/tree/master/"

def custom_doc_links(name): return None
