# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03_geometry.ipynb (unless otherwise specified).

__all__ = []

# Cell

import tensorflow as tf
from tensorflow.keras import models, layers
import tensorflow_addons as tfa

import numpy as np